Kwabena/fix can
openmv/micropython pull request #67
Opened 2020-04-21 06:34 UTC by kwagyeman

2020-04-21 16:20 UTC, iabdalkader requested changes

2020-04-21 16:20 UTC, iabdalkader commented on ports/stm32/fdcan.c
> +    while ((*rxf & FDCAN_RXF0S_F0FL) == 0) {
Can you please use FDCAN_RXF1S_F1FL for FIFO1 ? Yes they're the same mask, but still. Could use a variable for the mask.

2020-04-21 16:20 UTC, iabdalkader commented on ports/stm32/fdcan.c
> +    volatile uint32_t *rxf, *rxa, sa;
`sa` is not needed.. see the other comments.

2020-04-21 16:20 UTC, iabdalkader commented on ports/stm32/fdcan.c
> +    uint32_t index = (*rxf & FDCAN_RXF0S_F0GI) >> FDCAN_RXF0S_F0GI_Pos;
Please uses FIFO0 flags/mask for FIFO0 and FIFO1 flags/masks for FIFO1...
And use can->Init.RxFifoxElmtSize:
```
if (fifo == FDCAN_RX_FIFO0) {
index = (*rxf & FDCAN_RXF0S_F0GI) >> FDCAN_RXF0S_F0GI_Pos;
address = (uint32_t*)(can->msgRam.RxFIFO0SA + (index * can->Init.RxFifo0ElmtSize * 4));
} else {
index = (*rxf & FDCAN_RXF1S_F1GI) >> FDCAN_RXF1S_F1GI_Pos;
address = (uint32_t*)(can->msgRam.RxFIFO1SA + (index * can->Init.RxFifo1ElmtSize * 4));
}
```

2020-04-21 16:29 UTC, iabdalkader commented on ports/stm32/pyb_can.c
> +    uint32_t Timeout = args[ARG_timeout].u_int;
please rename Timeout to timeout_ms.

2020-04-22 15:49 UTC, kwagyeman commented on ports/stm32/pyb_can.c
> +    uint32_t Timeout = args[ARG_timeout].u_int;
Fixed.

2020-04-22 15:56 UTC, kwagyeman commented on ports/stm32/fdcan.c
> +    while ((*rxf & FDCAN_RXF0S_F0FL) == 0) {
Done

2020-04-22 15:58 UTC, kwagyeman commented on ports/stm32/fdcan.c
> +    uint32_t index = (*rxf & FDCAN_RXF0S_F0GI) >> FDCAN_RXF0S_F0GI_Pos;
Done

2020-04-22 17:29 UTC, iabdalkader requested changes

2020-04-22 17:29 UTC, iabdalkader commented on ports/stm32/fdcan.c
> +        if (timeout_ms == 0) {
I think timeout_ms == 0 means No timeout.. This loop should stay the same except for fixing the flag.

2020-04-22 17:29 UTC, iabdalkader commented on ports/stm32/pyb_can.c
> +    uint32_t timeout_ms = args[ARG_timeout].u_int;
The behavior of timeout is actually documented [here](http://docs.micropython.org/en/latest/library/pyb.CAN.html?highlight=can#pyb.CAN.send):
`If timeout is 0 the message is placed in a buffer in one of three hardware buffers and the method returns immediately. If all three buffers are in use an exception is thrown. If timeout is not 0, the method waits until the message is transmitted. If the message can’t be transmitted within the specified time an exception is thrown.`

2020-04-22 18:41 UTC, kwagyeman commented
It matches now.

2020-04-22 20:28 UTC, merged